# Generated by Django 5.0.4 on 2024-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('snapshot', models.CharField(max_length=200)),
                ('repositoryLink', models.URLField()),
                ('start', models.DateField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
    ]
