# Generated by Django 5.0.4 on 2024-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_lastupdate_projects_last_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='last_update',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start',
            field=models.DateField(),
        ),
    ]
