# Generated by Django 5.0.4 on 2024-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_options_alter_projects_last_update_and_more'),
        ('skills', '0002_alter_skills_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(to='skills.skills'),
        ),
    ]
