# Generated by Django 5.0.6 on 2024-05-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_last_update_alter_projects_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
