services:
  db:
    image: postgres:16.2
    restart: on-failure:3
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./keycloak_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
 
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [ "start-dev" ]
    ports:
      - 8080:8080
    depends_on:
      - db

  adminer:
    image: adminer
    restart: on-failure:3
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8081:8080

