# Generated by Django 5.0.4 on 2024-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
