# Generated by Django 5.0.4 on 2024-04-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_description_alter_pages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='url',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
