# Generated by Django 5.0.4 on 2024-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pages_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='url',
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
