# Generated by Django 5.0.4 on 2024-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_pages_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
