# Generated by Django 5.0.4 on 2024-04-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('pages', '0008_alter_pages_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.images'),
        ),
    ]
