# Generated by Django 5.0.4 on 2024-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('alt', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'Images',
            },
        ),
    ]
